import { ICommand } from '@distributed-social-platform/shared-kernel'

/**
 * Step 1 of the AI-Query Saga: hold credit without charging it.
 *
 * `reservationId` is generated by the saga (not here) because the compensation
 * descriptor has to carry it, and the saga is what knows both sides.
 * occ: repo.save catches P2002 on @@unique([aggregateId, version]).
 */
export class ReserveCreditsCommand implements ICommand {
  readonly name = ReserveCreditsCommand.name

  constructor(
    public readonly orgId: string,
    public readonly userId: string,
    public readonly reservationId: string,
    public readonly amount: number,
    public readonly reason: string,
  ) {}
}
